### PR TITLE
Update to use FetchContent_MakeAvailable, and avoid build errors due to using the same directory and now use unique directory

### PR DESCRIPTION
**Pull request by salmanmkc**
**Pull Request Template**

**Summary**

* Briefly describe the changes made in this pull request:
  + FetchContent_Populate is deprecated, so migrate to use FetchContent_MakeAvailable
  + I got errors when buildling for the first time, regarding the directory, this change fixed it for me.

**Changes**

* Describe the changes made in this pull request:
  + Few changes in Cmake file

**Motivation**

* Explain the motivation behind making these changes:
  + Improve experience when onboarding and building

**Testing**

* Describe the testing performed to verify the changes:
  + [Insert testing details]
  + Include information about:
    - Test cases added or modified
    - Results of testing

**Checklist**

* Confirm that the following have been completed:
  + [ ] Code compiles and runs successfully on all supported platforms
  + [ ] All tests pass
  + [ ] Documentation is updated (if applicable)
  + [ ] Changes follow the project's coding standards

**Additional Comments**

* Any additional comments or information that may be helpful:
  + [Insert additional comments]

### CODE REVIEW

**Comment by ASchneiderMeta** [comment]
What was the build error you were getting?

**Comment by leapally** [comment]
Hi @salmanmkc, thank you for reporting this issue sorry for the delay in processing your pull request.

We would like to repro the build error you were seeing so that we can test that this change fixes the issue.

Could you share with us information that you think might help us repro the error you were seeing?  Please find example information that may help us below:

- Type of system you are running build on
  - e.g. x86-64 Ubuntu 24.04 LTS)

- How the build was performed
  - Command used
    - e.g. Ocean's build script or direct call to cmake?

- Any guesses about what is different about your system that may contribute to this behavior
  - CMake version
  - Environment variables that modify CMake behavior

**Comment by ASchneiderMeta** [comment]
Commit https://github.com/facebookresearch/ocean/commit/8a75b0e386e924e835c0a2a89285ef48f76c2c98 should resolve the warning about deprecated usage of FetchContent_Populate(). It was addressed by the upstream provider and we updated to their latest release.

**Comment by salmanmkc** [comment]
Hey, yeah sorry I did not get round to finishing this PR, I realised that there was more to be done but have been busy with other work/projects. though I see in commit https://github.com/facebookresearch/ocean/commit/8a75b0e386e924e835c0a2a89285ef48f76c2c98 @leapally that FetchContent_Populate is still used, would that not be a problem when it becomes depreciated? Sorry typing this from a train so I don't have much insight right now and just remmebered I need to reply to this.

**Comment by salmanmkc** [comment]
> Only the single-argument version of FetchContent_Populate is deprecated: https://cmake.org/cmake/help/latest/module/FetchContent.html#:~:text=The%20command%20supports,use%20FetchContent_MakeAvailable()%20instead.
> 
> You mentioned another build error, related to needing a unique directory name. Could you provide more detail?

that was when trying to make a workaround, but I think the fix that you have mentioned is better in this case, I can close this I guess in this case. I will test out the fix mentioned though, thanks! Sorry for the extra work.

**Pull request closed without merging**
